FROM gradle:8.5-jdk21 AS build

COPY --chown=gradle:gradle MedHeadBackEnd /MedHeadBackEnd

WORKDIR /MedHeadBackEnd

RUN gradle build --no-daemon --scan -x test

FROM openjdk:21

COPY --from=build /MedHeadBackEnd/build/libs/emergency-0.0.1-SNAPSHOT.jar /app/emergency.jar

ENTRYPOINT ["java", "-Dspring.profiles.active=test", "-jar", "/app/emergency.jar"]