name: Check - FrontEnd
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-end-to-end:
    strategy:
       matrix:
         name: [Windows, Linux, MacOS]
         include:
           - name: Windows
             os: windows-latest
             java-version: 21
           - name: Linux
             os: ubuntu-latest
             java-version: 21
           - name: MacOS
             os: macos-latest
             java-version: 21
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Tests
        run: |
          cd MedHeadFrontEnd/selenium
          ./gradlew test

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: end-to-end tests
          path: |
            **/build/reports/
            **/build/test-results/