name : Check - FrontEnd

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd MedHeadFrontEnd/medheadfrontend
          npm install

      - name: Execute Node Build
        run: |
          cd MedHeadFrontEnd/medheadfrontend
          npm run build

      - name: Store production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: |
            **/build/static/js/
            **/build/static/css/

      - name: Execute Node Tests
        run: |
          cd MedHeadFrontEnd/medheadfrontend
          npm run test