name: Check - FrontEnd
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-frontend:
    strategy:
      matrix:
        name: [Windows, Linux, MacOS]
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: MacOS
            os: macos-latest
    runs-on: ${{ matrix.os }}

#  tests-frontend:
#    strategy:
#      matrix:
#        name: [NodeJS]
#        include:
#          - name: NodeJS
#            os: ubuntu-latest
#            node: [12.x]


#TODO