name: Check - FrontEnd
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-frontend:
    strategy:
      matrix:
        name: [Windows, Linux, MacOS]
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: MacOS
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Backend
        run: |
              cd MedHeadBackEnd
              ./gradlew run --args='--spring.profiles.active=test'

      - name: Run FrontEnd
        run: |
              cd MedHeadFrontEnd/medheadfrontend
              npm start

      - name: Execute Selenium Tests
        run: |
              cd MedHeadFrontEnd/selenium
              ./gradlew test